### ISSUE TITLE
Uncaught TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by smlu** [leny/atom-w3c-validation#6] opened 2015-05-19 13:19 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10.3
**Thrown From**: [w3c-validation](https://github.com/leny/atom-w3c-validation) package, v0.1.3
### Stack Trace

Uncaught TypeError: Cannot read property 'trim' of undefined

```
At /Users//.atom/packages/w3c-validation/lib/validator.coffee:52

TypeError: Cannot read property 'trim' of undefined
  at oOptions.callback (/Users//.atom/packages/w3c-validation/lib/validator.coffee:52:83)
  at /Users//.atom/packages/w3c-validation/node_modules/w3cvalidator/lib/w3cjs.js:82:13
  at Request.callback (/Users//.atom/packages/w3c-validation/node_modules/w3cvalidator/node_modules/superagent/lib/node/index.js:630:3)
  at Request.<anonymous> (/Users//.atom/packages/w3c-validation/node_modules/w3cvalidator/node_modules/superagent/lib/node/index.js:131:10)
  at emitOne (events.js:77:13)
  at Request.emit (events.js:166:7)
  at IncomingMessage.<anonymous> (/Users//.atom/packages/w3c-validation/node_modules/w3cvalidator/node_modules/superagent/lib/node/index.js:773:12)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:163:7)
  at _stream_readable.js:891:16
  at process._tickCallback (node.js:357:13)

```
### Commands

```
     -8:03.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-seti-ui)
     -7:56.8.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-seti-ui)
     -0:43.1.0 pane:reopen-closed-item (div.settings-view.pane-item)
     -0:14.1.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.2.0
atom-beautify, v0.27.1
autocomplete-clang, v0.6.9
autocomplete-paths, v1.0.2
color-picker, v1.7.0
function-name-in-status-bar, v0.2.6
ionic-atom, v0.3.1
keyboard-localization, v1.3.1
linter, vundefined
linter-clang, v2.25.1
log-console, v0.1.2
minimap, v4.9.0
minimap-bookmarks, v0.1.0
monokai, v0.14.0
script, v2.23.0
script-runner, vundefined
seti-ui, v0.7.1
w3c-validation, v0.1.3

# Dev
No dev packages
```

**Comment by leny** [comment] 2015-05-24 16:11
Hi, sorry for the long delay. I can't reproduce the error since some corrections made to fix the API v1.0 deprecation warnings.

Seems to be fixed in 0.2.0. Thanks for the report.

**Closed as completed by leny** 2015-05-24 16:11 UTC
